QUIZ_BANK = {
    "coding": {
        "easy": [
            {
                "question": "You need to remove duplicates from a list while keeping the original order. What is the simplest Python approach?",
                "options": [
                    "Use a set only",
                    "Use a loop plus a seen set",
                    "Sort the list first",
                    "Convert it to a dict without keys",
                ],
                "correct_index": 1,
                "explanation": "A loop plus a seen set preserves order and removes duplicates.",
                "option_feedback": [
                    "A set removes duplicates but loses order.",
                    "Correct: use a loop with a seen set to preserve order.",
                    "Sorting changes the original order.",
                    "A dict without keys is not a valid approach here.",
                ],
            },
            {
                "question": "Which algorithmic idea helps when you need to check whether an item exists in a sorted list quickly?",
                "options": [
                    "Linear scan",
                    "Binary search",
                    "Bubble sort",
                    "Backtracking",
                ],
                "correct_index": 1,
                "explanation": "Binary search is efficient on sorted lists.",
                "option_feedback": [
                    "Linear scan is slower for large sorted lists.",
                    "Correct: binary search is fast on sorted data.",
                    "Bubble sort is a sorting algorithm, not a search strategy.",
                    "Backtracking is used for combinatorial search problems.",
                ],
            },
            {
                "question": "You want to count how many times each interview skill appears in a list. What structure is best?",
                "options": ["List", "Tuple", "Dictionary or Counter", "Set"],
                "correct_index": 2,
                "explanation": "Dictionary-based counting or collections.Counter is best for frequency counts.",
                "option_feedback": [
                    "A list does not count values efficiently.",
                    "Tuples are not designed for counting.",
                    "Correct: dictionaries or Counter are ideal for frequencies.",
                    "A set only keeps unique values.",
                ],
            },
        ],
        "medium": [
            {
                "question": "A function should return early when input is invalid instead of nesting many if statements. Why is that better?",
                "options": [
                    "It makes the code shorter only",
                    "It improves readability and control flow",
                    "It always improves speed dramatically",
                    "It removes the need for testing",
                ],
                "correct_index": 1,
                "explanation": "Early returns keep code flatter and easier to read.",
                "option_feedback": [
                    "Shorter code is not the only benefit.",
                    "Correct: readability and cleaner control flow improve.",
                    "Performance is not the main reason.",
                    "Testing is still required.",
                ],
            },
            {
                "question": "You need to process a large file line by line instead of loading it all at once. What is the best approach?",
                "options": [
                    "Read the full file into memory",
                    "Use a generator or streaming loop",
                    "Convert it to JSON first",
                    "Copy the file repeatedly",
                ],
                "correct_index": 1,
                "explanation": "Streaming or generators avoid loading everything into memory.",
                "option_feedback": [
                    "That can waste memory for large files.",
                    "Correct: stream the file or use a generator.",
                    "Converting to JSON does not solve memory use.",
                    "Copying the file is unrelated and inefficient.",
                ],
            },
            {
                "question": "You are asked to implement retry logic for a flaky API. Which design is best?",
                "options": [
                    "Hide all failures",
                    "Add a helper with clear retry limits and backoff",
                    "Retry forever in a loop",
                    "Ignore the response status",
                ],
                "correct_index": 1,
                "explanation": "A helper with bounded retries and backoff is more reliable and maintainable.",
                "option_feedback": [
                    "Hiding failures makes debugging harder.",
                    "Correct: bounded retries with backoff are safer.",
                    "Infinite retry loops can hang the app.",
                    "Ignoring status codes breaks reliability.",
                ],
            },
        ],
        "hard": [
            {
                "question": "You need the top K scoring candidates from a live stream of results. Which approach is usually best?",
                "options": [
                    "Store everything and sort at the end",
                    "Use a min-heap of size K",
                    "Use recursion only",
                    "Convert the stream to a set",
                ],
                "correct_index": 1,
                "explanation": "A min-heap of size K is efficient for keeping the top K items.",
                "option_feedback": [
                    "Sorting everything is more expensive than necessary.",
                    "Correct: a min-heap keeps the top K efficiently.",
                    "Recursion is not the right tool here.",
                    "A set removes duplicates but does not rank values.",
                ],
            },
            {
                "question": "You have to design a function that scales to millions of records. What matters most?",
                "options": [
                    "Only syntax style",
                    "Time and space complexity",
                    "Variable naming only",
                    "Using the longest possible code",
                ],
                "correct_index": 1,
                "explanation": "For large data, time and space complexity are the key concerns.",
                "option_feedback": [
                    "Style matters, but not as the main scaling factor.",
                    "Correct: complexity determines scalability.",
                    "Naming helps readability, not scalability.",
                    "Longer code is not better.",
                ],
            },
            {
                "question": "You are comparing two sorted arrays and need the first common item efficiently. Which pattern fits best?",
                "options": [
                    "Two-pointer technique",
                    "Nested brute-force loops",
                    "Random guessing",
                    "Hashing every item into a string",
                ],
                "correct_index": 0,
                "explanation": "Two pointers are efficient for comparing sorted arrays.",
                "option_feedback": [
                    "Correct: two pointers work well on sorted arrays.",
                    "Nested loops are slower than necessary.",
                    "Random guessing is not an algorithm.",
                    "String hashing is not the right idea here.",
                ],
            },
        ],
    },
    "python": {
        "easy": [
            {
                "question": 'Your API returns the string "hello" and you want to confirm its size before validating input. What does len("hello") return?',
                "options": ["3", "4", "5", "6"],
                "correct_index": 2,
                "explanation": 'The word hello has 5 characters, so len("hello") returns 5.',
                "option_feedback": [
                    "Too small: that would only count part of the word.",
                    "Too small for the full string.",
                    "Correct: all 5 characters are counted.",
                    "Too large for the word hello.",
                ],
            },
            {
                "question": "You need to create a reusable helper for formatting interview feedback. Which keyword defines a Python function?",
                "options": ["func", "def", "function", "lambda"],
                "correct_index": 1,
                "explanation": "Python uses def to define a named function.",
                "option_feedback": [
                    "func is not a Python keyword.",
                    "Correct: def defines a function block.",
                    "function is not a Python keyword.",
                    "lambda creates an anonymous function, not a named definition.",
                ],
            },
            {
                "question": "You are storing a candidate’s planned practice tasks and want to reorder them later. Which type is ordered and mutable?",
                "options": ["tuple", "list", "set", "dict"],
                "correct_index": 1,
                "explanation": "Lists preserve order and can be changed after creation.",
                "option_feedback": [
                    "Tuples keep order but cannot be changed.",
                    "Correct: lists are ordered and mutable.",
                    "Sets are unordered and do not preserve sequence.",
                    "Dicts store key-value pairs, not a simple ordered sequence for this case.",
                ],
            },
            {
                "question": "Your script reads user names from a file and must skip blank lines cleanly. What is the simplest approach?",
                "options": [
                    "Use a for loop with strip() and continue on empty strings",
                    "Convert everything to a tuple",
                    "Call eval() on each line",
                    "Always use recursion",
                ],
                "correct_index": 0,
                "explanation": "A loop with strip() and a blank-line check is the most direct and safe approach.",
                "option_feedback": [
                    "Correct: it is readable, safe, and easy to maintain.",
                    "Tuples do not solve blank-line handling.",
                    "eval() is unsafe and unrelated to parsing lines.",
                    "Recursion is unnecessary for simple file iteration.",
                ],
            },
        ],
        "medium": [
            {
                "question": "Your logging pipeline stores tags that should never change after creation, while task queues need edits. What is the correct statement?",
                "options": [
                    "Lists are immutable, tuples are mutable",
                    "Lists are mutable, tuples are immutable",
                    "Both are immutable",
                    "Both are mutable",
                ],
                "correct_index": 1,
                "explanation": "Lists can be changed after creation, tuples cannot.",
                "option_feedback": [
                    "Incorrect: lists can be modified.",
                    "Correct: mutable list, immutable tuple.",
                    "Both are not immutable because lists can change.",
                    "Tuples cannot be modified, so both mutable is wrong.",
                ],
            },
            {
                "question": "You want to transform a list of interview scores into pass/fail labels in one line. What is list comprehension best for?",
                "options": [
                    "Creating classes",
                    "Writing compact loops",
                    "Compiling code",
                    "Managing imports",
                ],
                "correct_index": 1,
                "explanation": "List comprehensions are a compact way to build new lists from existing iterables.",
                "option_feedback": [
                    "Classes are unrelated.",
                    "Correct: it creates concise loops and new lists.",
                    "It does not compile code.",
                    "Imports are not the main use case.",
                ],
            },
            {
                "question": "Your interview app needs separate package versions for backend and scripts. What is the purpose of a virtual environment?",
                "options": [
                    "Run faster code",
                    "Isolate project dependencies",
                    "Encrypt files",
                    "Replace pip",
                ],
                "correct_index": 1,
                "explanation": "Virtual environments isolate dependencies so projects do not conflict.",
                "option_feedback": [
                    "Virtual environments do not inherently speed up code.",
                    "Correct: they isolate dependencies per project.",
                    "Encryption is not the purpose.",
                    "They do not replace pip; they work with it.",
                ],
            },
            {
                "question": "You are writing a function that should not keep large results in memory if you only need to iterate once. What is the best choice?",
                "options": [
                    "Generator",
                    "Global variable",
                    "Static string",
                    "Nested class",
                ],
                "correct_index": 0,
                "explanation": "Generators yield values lazily, which keeps memory use lower.",
                "option_feedback": [
                    "Correct: generators produce values lazily and are memory-efficient.",
                    "Global variables make code harder to reason about.",
                    "A static string cannot represent a stream of values.",
                    "A nested class does not address memory-efficient iteration.",
                ],
            },
        ],
        "hard": [
            {
                "question": "Your interview analytics store nested dicts for each session. What is the difference between shallow copy and deep copy?",
                "options": [
                    "No difference",
                    "Shallow copy duplicates nested objects",
                    "Deep copy duplicates nested objects",
                    "Deep copy is slower because it skips nested objects",
                ],
                "correct_index": 2,
                "explanation": "A deep copy duplicates nested objects, while a shallow copy keeps references to them.",
                "option_feedback": [
                    "Incorrect: the behavior is very different.",
                    "That describes a deep copy, not a shallow one.",
                    "Correct: deep copy clones nested objects.",
                    "Deep copy is slower because it copies more data, not because it skips nested objects.",
                ],
            },
            {
                "question": "You are processing many CPU-heavy interview transcripts in Python threads. Why can the GIL matter in CPython?",
                "options": [
                    "It blocks all I/O",
                    "It limits true parallel execution of Python bytecode threads",
                    "It speeds up CPU-bound code",
                    "It is only used in Flask",
                ],
                "correct_index": 1,
                "explanation": "The GIL limits true parallel execution of Python bytecode threads in CPython.",
                "option_feedback": [
                    "Incorrect: I/O can still happen; the GIL mainly affects CPU-bound bytecode execution.",
                    "Correct: it limits true parallel execution of Python bytecode threads.",
                    "It does not speed up CPU-bound work.",
                    "It is a CPython runtime detail, not a Flask feature.",
                ],
            },
            {
                "question": "Your question generator should stream suggestions without building a large list first. What is a generator best used for?",
                "options": [
                    "Storing large datasets in memory",
                    "Creating values lazily",
                    "Replacing dictionaries",
                    "Running SQL queries",
                ],
                "correct_index": 1,
                "explanation": "Generators yield values lazily and are memory efficient.",
                "option_feedback": [
                    "Generators are not meant to preload huge datasets.",
                    "Correct: they create values on demand.",
                    "They do not replace dictionaries.",
                    "SQL queries are unrelated to the generator pattern.",
                ],
            },
            {
                "question": "You are designing retry logic for an API call. Which pattern is most suitable for keeping the function readable and reusable?",
                "options": [
                    "Hard-code everything inside one long function",
                    "Separate retry logic into a helper with clear limits",
                    "Use nested loops without conditions",
                    "Avoid exception handling entirely",
                ],
                "correct_index": 1,
                "explanation": "A helper function with clear retry limits keeps the code readable and testable.",
                "option_feedback": [
                    "Long functions are harder to test and maintain.",
                    "Correct: extracted helpers improve readability and reuse.",
                    "Nested loops without clear conditions are brittle.",
                    "Exception handling is essential for retries.",
                ],
            },
        ],
    },
    "sql": {
        "easy": [
            {
                "question": "A recruiter dashboard should only show interviews from this week. Which SQL clause filters rows?",
                "options": ["GROUP BY", "ORDER BY", "WHERE", "JOIN"],
                "correct_index": 2,
                "explanation": "WHERE filters rows based on conditions.",
                "option_feedback": [
                    "GROUP BY groups rows but does not filter them first.",
                    "ORDER BY sorts rows.",
                    "Correct: WHERE filters rows.",
                    "JOIN combines tables, not filter rows directly.",
                ],
            },
            {
                "question": "You want to pull candidate names from the database. What does SELECT do?",
                "options": [
                    "Deletes rows",
                    "Retrieves data",
                    "Creates tables",
                    "Updates records",
                ],
                "correct_index": 1,
                "explanation": "SELECT retrieves data from a table.",
                "option_feedback": [
                    "DELETE is the command for removing rows.",
                    "Correct: SELECT retrieves data.",
                    "CREATE TABLE makes a new table.",
                    "UPDATE changes existing records.",
                ],
            },
            {
                "question": "You want to see rows in descending order of interview score. Which clause should you use?",
                "options": ["WHERE", "ORDER BY", "HAVING", "DISTINCT"],
                "correct_index": 1,
                "explanation": "ORDER BY sorts the result set in ascending or descending order.",
                "option_feedback": [
                    "WHERE filters rows but does not sort them.",
                    "Correct: ORDER BY handles sorting.",
                    "HAVING filters grouped results.",
                    "DISTINCT removes duplicates.",
                ],
            },
        ],
        "medium": [
            {
                "question": "Your analytics page needs average score per topic. What is the purpose of GROUP BY?",
                "options": [
                    "Sorts rows",
                    "Aggregates rows into groups",
                    "Deletes duplicates",
                    "Creates indexes",
                ],
                "correct_index": 1,
                "explanation": "GROUP BY groups rows so aggregate functions can summarize each group.",
                "option_feedback": [
                    "Sorting is done with ORDER BY.",
                    "Correct: GROUP BY creates groups for aggregation.",
                    "DISTINCT removes duplicates.",
                    "Indexes are created separately.",
                ],
            },
            {
                "question": "You are joining interview sessions with candidate profiles. What does an INNER JOIN return?",
                "options": [
                    "All rows from both tables",
                    "Matching rows from both tables",
                    "Only unmatched rows",
                    "Only rows from the left table",
                ],
                "correct_index": 1,
                "explanation": "INNER JOIN returns only rows that match in both tables.",
                "option_feedback": [
                    "That sounds like a FULL OUTER JOIN.",
                    "Correct: INNER JOIN keeps matching rows from both tables.",
                    "Unmatched rows are not included.",
                    "That is closer to a LEFT JOIN.",
                ],
            },
            {
                "question": "You need all candidates even if some have no quiz history yet. Which join should you think of first?",
                "options": ["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "NATURAL JOIN"],
                "correct_index": 1,
                "explanation": "LEFT JOIN keeps all rows from the left table and matches from the right when available.",
                "option_feedback": [
                    "INNER JOIN drops rows without matches.",
                    "Correct: LEFT JOIN keeps every candidate row.",
                    "CROSS JOIN creates every combination and is not the goal.",
                    "NATURAL JOIN is implicit and risky for this use case.",
                ],
            },
        ],
        "hard": [
            {
                "question": "You need the latest interview result for each candidate without collapsing all rows. When would you use a window function?",
                "options": [
                    "To delete duplicate tables",
                    "To perform calculations across a set of rows related to the current row",
                    "To replace WHERE",
                    "To encrypt columns",
                ],
                "correct_index": 1,
                "explanation": "Window functions let you calculate across related rows without collapsing the result set.",
                "option_feedback": [
                    "Window functions do not delete tables.",
                    "Correct: they compute across related rows while keeping detail rows.",
                    "They do not replace WHERE filters.",
                    "Encryption is unrelated.",
                ],
            },
            {
                "question": "Your dashboard query is slow when filtering by candidate_id. What is the main purpose of an index?",
                "options": [
                    "Store backup copies",
                    "Improve query read performance for lookups",
                    "Increase row size",
                    "Replace primary keys",
                ],
                "correct_index": 1,
                "explanation": "Indexes speed up lookups, but they can add overhead on inserts and updates.",
                "option_feedback": [
                    "Indexes are not backups.",
                    "Correct: they improve lookup performance.",
                    "Row size does not increase because of the purpose of the index.",
                    "Indexes support keys but do not replace primary keys.",
                ],
            },
            {
                "question": "You need the top 3 scoring candidates per department. Which SQL feature is the cleanest fit?",
                "options": [
                    "Window function with ROW_NUMBER()",
                    "DROP TABLE",
                    "UNION ALL only",
                    "Cartesian product",
                ],
                "correct_index": 0,
                "explanation": "Window functions like ROW_NUMBER() are ideal for ranking rows within partitions such as departments.",
                "option_feedback": [
                    "Correct: ROW_NUMBER() can rank rows within each department.",
                    "DROP TABLE would delete data.",
                    "UNION ALL does not solve ranking.",
                    "A Cartesian product would create irrelevant row combinations.",
                ],
            },
        ],
    },
    "aptitude": {
        "easy": [
            {
                "question": "A candidate drives 60 km to an interview in 1 hour. What is the speed?",
                "options": ["30 km/h", "40 km/h", "60 km/h", "80 km/h"],
                "correct_index": 2,
                "explanation": "Speed = distance / time = 60 km/h.",
                "option_feedback": [
                    "That is too low for 60 km in 1 hour.",
                    "That is still too low.",
                    "Correct: 60 km in 1 hour equals 60 km/h.",
                    "Too high for this calculation.",
                ],
            },
            {
                "question": "Your mock test has 200 marks and a candidate scores 25% of them. What is the score?",
                "options": ["25", "40", "50", "60"],
                "correct_index": 2,
                "explanation": "25% of 200 is 50.",
                "option_feedback": [
                    "That is 12.5% of 200.",
                    "That is 20% of 200.",
                    "Correct: 25% of 200 is 50.",
                    "That is 30% of 200.",
                ],
            },
            {
                "question": "A team completes 100 practice questions in 5 days. How many questions per day on average?",
                "options": ["10", "15", "20", "25"],
                "correct_index": 2,
                "explanation": "100 divided by 5 is 20 questions per day.",
                "option_feedback": [
                    "Too low for this workload.",
                    "Still too low.",
                    "Correct: 100 / 5 = 20.",
                    "Too high for 100 questions over 5 days.",
                ],
            },
        ],
        "medium": [
            {
                "question": "A worker finishes a task in 12 days. How much work is done in 3 days?",
                "options": ["1/2", "1/3", "1/4", "1/6"],
                "correct_index": 2,
                "explanation": "3 out of 12 days is one quarter of the work.",
                "option_feedback": [
                    "Half would be 6 days, not 3.",
                    "A third would be 4 days.",
                    "Correct: 3/12 = 1/4.",
                    "One sixth would be 2 days.",
                ],
            },
            {
                "question": "In a batch of 40 trainees, the ratio of boys to girls is 3:5. How many girls are there?",
                "options": ["15", "20", "25", "30"],
                "correct_index": 2,
                "explanation": "Total parts = 8, each part = 5, girls = 5 parts = 25.",
                "option_feedback": [
                    "That is 3 parts, not 5.",
                    "That is not enough for 5 parts.",
                    "Correct: 5 out of 8 parts of 40 is 25.",
                    "That would be too many girls.",
                ],
            },
            {
                "question": "A candidate answers 18 questions correctly out of 24. What is the accuracy percentage?",
                "options": ["60%", "70%", "75%", "80%"],
                "correct_index": 2,
                "explanation": "18 divided by 24 equals 0.75, which is 75%.",
                "option_feedback": [
                    "Too low for 18 out of 24.",
                    "Still too low.",
                    "Correct: 18/24 = 75%.",
                    "That would be 19.2/24.",
                ],
            },
        ],
        "hard": [
            {
                "question": "A and B can finish a job in 10 and 15 days respectively. How long together?",
                "options": ["5 days", "6 days", "7.5 days", "8 days"],
                "correct_index": 1,
                "explanation": "Combined rate = 1/10 + 1/15 = 1/6, so they finish in 6 days.",
                "option_feedback": [
                    "Too fast for their combined work rate.",
                    "Correct: together they finish in 6 days.",
                    "Too slow for the combined rate.",
                    "Still too slow for the combined rate.",
                ],
            },
            {
                "question": "If a number increases by 20% and then decreases by 20%, what is the net effect?",
                "options": ["No change", "4% increase", "4% decrease", "20% decrease"],
                "correct_index": 2,
                "explanation": "The net effect is a 4% decrease because the second change is applied to the larger value.",
                "option_feedback": [
                    "Not quite: the final value is lower than the original.",
                    "It is not an increase.",
                    "Correct: the net effect is a 4% decrease.",
                    "That would be too large a decrease.",
                ],
            },
            {
                "question": "A project has 120 interview prep tasks. If 25% are completed in the first week, how many remain?",
                "options": ["80", "90", "100", "110"],
                "correct_index": 1,
                "explanation": "25% of 120 is 30, so 120 - 30 = 90 remain.",
                "option_feedback": [
                    "This is too low; if 30 are done, 90 remain.",
                    "Correct: 30 done, 90 remain.",
                    "This is too high for the remaining count.",
                    "This is too high for the remaining count.",
                ],
            },
        ],
    },
    "hr": {
        "easy": [
            {
                "question": 'The interviewer says, "Tell me about yourself." What structure is strongest?',
                "options": [
                    "Random facts",
                    "Past, present, future",
                    "Just education",
                    "Only hobbies",
                ],
                "correct_index": 1,
                "explanation": "A clear intro uses past, present, and future.",
                "option_feedback": [
                    "Random facts feel unstructured.",
                    "Correct: past, present, future keeps the answer focused.",
                    "Education alone is too narrow.",
                    "Hobbies alone do not explain your fit for the role.",
                ],
            },
            {
                "question": "Before a real interview, what is the most useful preparation step?",
                "options": [
                    "Arrive late",
                    "Research the company",
                    "Ignore the job description",
                    "Speak as fast as possible",
                ],
                "correct_index": 1,
                "explanation": "Company research helps you answer with context and relevance.",
                "option_feedback": [
                    "Arriving late makes a bad impression.",
                    "Correct: company research improves answer quality.",
                    "Ignoring the job description weakens your answers.",
                    "Speaking too fast hurts clarity.",
                ],
            },
            {
                "question": "You are asked about your strengths. What makes the answer stronger?",
                "options": [
                    'Only saying "I work hard"',
                    "A strength plus a short example",
                    "Reading from notes word for word",
                    "Talking about salary",
                ],
                "correct_index": 1,
                "explanation": "A strength with a short example feels credible and specific.",
                "option_feedback": [
                    "Too vague and generic.",
                    "Correct: strength + example is stronger.",
                    "Reading word for word feels stiff.",
                    "Salary does not answer the question.",
                ],
            },
        ],
        "medium": [
            {
                "question": "Why should you avoid speaking negatively about previous employers?",
                "options": [
                    "It is always illegal",
                    "It can make you sound unprofessional",
                    "It improves clarity",
                    "It shows confidence",
                ],
                "correct_index": 1,
                "explanation": "Interviewers expect professionalism and maturity.",
                "option_feedback": [
                    "It is not automatically illegal in every context.",
                    "Correct: negativity can make you sound unprofessional.",
                    "It does not improve clarity.",
                    "It usually hurts your image more than it helps confidence.",
                ],
            },
            {
                "question": "What is a good way to answer weakness questions?",
                "options": [
                    "Say you have no weakness",
                    "Give a real weakness and show improvement",
                    "Blame the last company",
                    "Change the subject",
                ],
                "correct_index": 1,
                "explanation": "Show self-awareness and improvement.",
                "option_feedback": [
                    "Nobody believes that answer.",
                    "Correct: real weakness plus improvement is credible.",
                    "Blaming others sounds defensive.",
                    "Avoiding the question looks unprepared.",
                ],
            },
            {
                "question": "You missed a project deadline. What is the best interview response?",
                "options": [
                    "Hide the mistake",
                    "Own it, explain what changed, and describe the fix",
                    "Blame the team only",
                    "Say deadlines do not matter",
                ],
                "correct_index": 1,
                "explanation": "Strong answers show ownership, context, and a corrective action.",
                "option_feedback": [
                    "Hiding mistakes damages trust.",
                    "Correct: ownership and learning are the goal.",
                    "Blame shifts responsibility away from you.",
                    "This makes you sound careless.",
                ],
            },
        ],
        "hard": [
            {
                "question": "How do you handle a question you do not know?",
                "options": [
                    "Guess wildly",
                    "Stay calm, explain your thinking, and ask for clarification if needed",
                    "Remain silent",
                    "Change the topic",
                ],
                "correct_index": 1,
                "explanation": "Good candidates stay composed, explain their reasoning, and ask clarifying questions when needed.",
                "option_feedback": [
                    "Guessing can damage credibility.",
                    "Correct: calm reasoning and clarification show maturity.",
                    "Silence leaves the interviewer with nothing to assess.",
                    "Changing the topic avoids the question.",
                ],
            },
            {
                "question": "What makes a leadership answer stronger?",
                "options": [
                    "More jargon",
                    "Specific actions and measurable outcomes",
                    "Vague statements",
                    "Very long answers",
                ],
                "correct_index": 1,
                "explanation": "Leadership answers need ownership, actions, and measurable outcomes.",
                "option_feedback": [
                    "Jargon does not prove leadership.",
                    "Correct: actions plus outcomes are convincing.",
                    "Vague statements are too weak.",
                    "Long answers are not automatically stronger.",
                ],
            },
            {
                "question": "You are asked why you want this role. Which answer is best?",
                "options": [
                    "It sounds easy",
                    "It matches my skills and the company’s direction",
                    "I just need any job",
                    "The title looks nice",
                ],
                "correct_index": 1,
                "explanation": "A strong answer connects your skills to the role and the company.",
                "option_feedback": [
                    "Sounding easy is not a serious reason.",
                    "Correct: fit plus direction is a strong answer.",
                    "This sounds transactional and weak.",
                    "A title alone is not enough.",
                ],
            },
        ],
    },
}
