SKILL_KEYWORDS = {
    "languages": [
        "python",
        "javascript",
        "java",
        "c++",
        "c#",
        "ruby",
        "go",
        "rust",
        "typescript",
        "kotlin",
        "swift",
        "php",
        "scala",
        "r",
        "matlab",
        "perl",
        "bash",
        "shell",
        "dart",
        "elixir",
        "haskell",
    ],
    "frameworks": [
        "react",
        "angular",
        "vue",
        "django",
        "flask",
        "fastapi",
        "spring",
        "express",
        "node",
        "nodejs",
        "next.js",
        "nuxt",
        "svelte",
        "laravel",
        "rails",
        "asp.net",
        "tensorflow",
        "pytorch",
        "keras",
        "scikit-learn",
        "pandas",
        "numpy",
        "fastapi",
        "graphql",
        "rest",
        "redux",
        "tailwind",
    ],
    "databases": [
        "mysql",
        "postgresql",
        "mongodb",
        "redis",
        "sqlite",
        "oracle",
        "cassandra",
        "elasticsearch",
        "dynamodb",
        "firebase",
        "supabase",
        "neo4j",
        "influxdb",
        "mariadb",
        "sql server",
    ],
    "cloud_devops": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "jenkins",
        "git",
        "github",
        "gitlab",
        "ci/cd",
        "terraform",
        "ansible",
        "linux",
        "nginx",
        "apache",
        "heroku",
        "vercel",
        "netlify",
        "cloudflare",
    ],
    "tools": [
        "jira",
        "confluence",
        "slack",
        "figma",
        "postman",
        "swagger",
        "vs code",
        "intellij",
        "xcode",
        "android studio",
        "jupyter",
        "tableau",
        "power bi",
        "excel",
        "git",
        "webpack",
        "vite",
    ],
}

EDUCATION_KEYWORDS = [
    "bachelor",
    "master",
    "phd",
    "doctorate",
    "b.sc",
    "m.sc",
    "b.tech",
    "m.tech",
    "mba",
    "b.e",
    "m.e",
    "degree",
    "diploma",
    "certification",
    "certificate",
    "university",
    "college",
    "institute",
    "school",
    "computer science",
    "information technology",
    "engineering",
    "graduate",
]

EXPERIENCE_PATTERNS = [
    r"(\d+)\+?\s*years?(?:\s+(?:of\s+)?experience)?",
    r"(\d+)\+?\s*years?\s+(?:of\s+)?experience",
    r"experience\s+(?:of\s+)?(\d+)\+?\s*years?",
    r"(\d+)\+?\s*yrs?\s+(?:of\s+)?experience",
]
